Version: 02.14.2023

# Capstone Project: Bringing It All Together

In this lab, you will bring together many of the tools and techniques that you have learned throughout this course into a final project. You can choose from many different paths to get to the solution. You could use AWS Managed Services, such as Amazon Comprehend, or use the Amazon SageMaker models. Have fun on whichever path you choose.

### Business scenario

You work for a training organization that recently developed an introductory course about machine learning (ML). The course includes more than 40 videos that cover a broad range of ML topics. You have been asked to create an application that will students can use to quickly locate and view video content by searching for topics and key phrases.

You have downloaded all of the videos to an Amazon Simple Storage Service (Amazon S3) bucket. Your assignment is to produce a dashboard that meets your supervisor’s requirements.

To assist you, all of the previous labs have been provided in this workspace.

## Lab steps

To complete this lab, you will follow these steps:

1. [Viewing the video files](#1.-Viewing-the-video-files)
2. [Transcribing the videos](#2.-Transcribing-the-videos)
3. [Normalizing the text](#3.-Normalizing-the-text)
4. [Extracting key phrases and topics](#4.-Extracting-key-phrases-and-topics)
5. [Creating the dashboard](#5.-Creating-the-dashboard)

## Submitting your work

1. In the lab console, choose **Submit** to record your progress and when prompted, choose **Yes**.

1. If the results don't display after a couple of minutes, return to the top of these instructions and choose **Grades**.

     **Tip**: You can submit your work multiple times. After you change your work, choose **Submit** again. Your last submission is what will be recorded for this lab.

1. To find detailed feedback on your work, choose **Details** followed by **View Submission Report**.

## Useful information

The following cell contains some information that might be useful as you complete this project.

In [ ]:
bucket = "<your bucket>"
job_data_access_role = 'arn:aws:iam::<your_role>'

## 1. Viewing the video files
([Go to top](#Capstone-8:-Bringing-It-All-Together))

The source video files are located in the following shared Amazon Simple Storage Service (Amazon S3) bucket.

In [18]:
!aws s3 ls s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/

2021-04-26 20:17:33  410925369 Mod01_Course Overview.mp4
2021-04-26 20:10:02   39576695 Mod02_Intro.mp4
2021-04-26 20:31:23  302994828 Mod02_Sect01.mp4
2021-04-26 20:17:33  416563881 Mod02_Sect02.mp4
2021-04-26 20:17:33  318685583 Mod02_Sect03.mp4
2021-04-26 20:17:33  255877251 Mod02_Sect04.mp4
2021-04-26 20:23:51   99988046 Mod02_Sect05.mp4
2021-04-26 20:24:54   50700224 Mod02_WrapUp.mp4
2021-04-26 20:26:27   60627667 Mod03_Intro.mp4
2021-04-26 20:26:28  272229844 Mod03_Sect01.mp4
2021-04-26 20:27:06  309127124 Mod03_Sect02_part1.mp4
2021-04-26 20:27:06  195635527 Mod03_Sect02_part2.mp4
2021-04-26 20:28:03  123924818 Mod03_Sect02_part3.mp4
2021-04-26 20:31:28  171681915 Mod03_Sect03_part1.mp4
2021-04-26 20:32:07  285200083 Mod03_Sect03_part2.mp4
2021-04-26 20:33:17  105470345 Mod03_Sect03_part3.mp4
2021-04-26 20:35:10  157185651 Mod03_Sect04_part1.mp4
2021-04-26 20:36:27  187435635 Mod03_Sect04_part2.mp4
2021-04-26 20:36:40  280720369 Mod03_Sect04_part3.mp4
2021-04-26 20:40:01  443479313 Mod03_Sect05.mp4
2021-04-26 20:40:08  234182186 Mod03_Sect06.mp4
2021-04-26 20:40:33  207718047 Mod03_Sect07_part1.mp4
2021-04-26 20:42:07  125592110 Mod03_Sect07_part2.mp4
2021-04-26 20:45:10  508500301 Mod03_Sect07_part3.mp4
2021-04-26 20:46:16  320126756 Mod03_Sect08.mp4
2021-04-26 20:46:43   41839508 Mod03_WrapUp.mp4
2021-04-26 20:46:55   34148489 Mod04_Intro.mp4
2021-04-26 20:48:24   84959465 Mod04_Sect01.mp4
2021-04-26 20:48:25  345182970 Mod04_Sect02_part1.mp4
2021-04-26 20:51:34  218661651 Mod04_Sect02_part2.mp4
2021-04-26 20:53:32  430140637 Mod04_Sect02_part3.mp4
2021-04-26 20:56:03   22036605 Mod04_WrapUp.mp4
2021-04-26 20:57:18   49187118 Mod05_Intro.mp4
2021-04-26 20:58:19  245798071 Mod05_Sect01_ver2.mp4
2021-04-26 20:58:50  233314835 Mod05_Sect02_part1_ver2.mp4
2021-04-26 20:59:14  348545306 Mod05_Sect02_part2.mp4
2021-04-26 20:59:17  239142711 Mod05_Sect03_part1.mp4
2021-04-26 21:06:04  267533559 Mod05_Sect03_part2.mp4
2021-04-26 21:06:06  212502220 Mod05_Sect03_part3.mp4
2021-04-26 21:06:48  206317022 Mod05_Sect03_part4_ver2.mp4
2021-04-26 21:06:48   60361230 Mod05_WrapUp_ver2.mp4
2021-04-26 21:09:14   35397860 Mod06_Intro.mp4
2021-04-26 21:09:24  845633599 Mod06_Sect01.mp4
2021-04-26 21:10:47  326126684 Mod06_Sect02.mp4
2021-04-26 21:12:26   19790740 Mod06_WrapUp.mp4
2021-04-26 21:12:56  131249036 Mod07_Sect01.mp4

## 2. Transcribing the videos
 ([Go to top](#Capstone-8:-Bringing-It-All-Together))

Use this section to implement your solution to transcribe the videos.

In [20]:
!aws s3 cp s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/ s3://{bucket}/input/ --recursive

copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Sect01.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect01.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Sect03.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect03.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Sect05.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect05.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_WrapUp.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_WrapUp.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Intro.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Intro.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Intro.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Intro.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Sect04.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect04.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect01.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect01.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect02_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod02_Sect02.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect02.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect02_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod01_Course Overview.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod01_Course Overview.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect02_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect03_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect03_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect04_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect04_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect03_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect04_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect06.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect06.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect07_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect07_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_WrapUp.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_WrapUp.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_Intro.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Intro.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_Sect01.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect01.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect05.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect05.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect08.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect08.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_WrapUp.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_WrapUp.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_Sect02_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_Sect02_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Intro.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Intro.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect02_part1_ver2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect02_part1_ver2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod03_Sect07_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect01_ver2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect01_ver2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod04_Sect02_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect03_part1.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part1.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect02_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect02_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod06_Intro.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Intro.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_WrapUp_ver2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_WrapUp_ver2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect03_part3.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part3.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect03_part2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod06_WrapUp.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_WrapUp.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod05_Sect03_part4_ver2.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part4_ver2.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod07_Sect01.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod07_Sect01.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod06_Sect02.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Sect02.mp4
copy: s3://aws-tc-largeobjects/CUR-TF-200-ACMNLP-1/video/Mod06_Sect01.mp4 to s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Sect01.mp4

In [21]:
from boto3 import client

conn = client('s3') 
for key in conn.list_objects(Bucket=bucket)['Contents']:
    print(key['Key'])

input/Mod01_Course Overview.mp4
input/Mod02_Intro.mp4
input/Mod02_Sect01.mp4
input/Mod02_Sect02.mp4
input/Mod02_Sect03.mp4
input/Mod02_Sect04.mp4
input/Mod02_Sect05.mp4
input/Mod02_WrapUp.mp4
input/Mod03_Intro.mp4
input/Mod03_Sect01.mp4
input/Mod03_Sect02_part1.mp4
input/Mod03_Sect02_part2.mp4
input/Mod03_Sect02_part3.mp4
input/Mod03_Sect03_part1.mp4
input/Mod03_Sect03_part2.mp4
input/Mod03_Sect03_part3.mp4
input/Mod03_Sect04_part1.mp4
input/Mod03_Sect04_part2.mp4
input/Mod03_Sect04_part3.mp4
input/Mod03_Sect05.mp4
input/Mod03_Sect06.mp4
input/Mod03_Sect07_part1.mp4
input/Mod03_Sect07_part2.mp4
input/Mod03_Sect07_part3.mp4
input/Mod03_Sect08.mp4
input/Mod03_WrapUp.mp4
input/Mod04_Intro.mp4
input/Mod04_Sect01.mp4
input/Mod04_Sect02_part1.mp4
input/Mod04_Sect02_part2.mp4
input/Mod04_Sect02_part3.mp4
input/Mod04_WrapUp.mp4
input/Mod05_Intro.mp4
input/Mod05_Sect01_ver2.mp4
input/Mod05_Sect02_part1_ver2.mp4
input/Mod05_Sect02_part2.mp4
input/Mod05_Sect03_part1.mp4
input/Mod05_Sect03_part2.mp4
input/Mod05_Sect03_part3.mp4
input/Mod05_Sect03_part4_ver2.mp4
input/Mod05_WrapUp_ver2.mp4
input/Mod06_Intro.mp4
input/Mod06_Sect01.mp4
input/Mod06_Sect02.mp4
input/Mod06_WrapUp.mp4
input/Mod07_Sect01.mp4

In [22]:
import boto3
import os, io, struct, json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import uuid
from time import sleep
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import RegexpTokenizer
from nltk.stem.wordnet import WordNetLemmatizer

[nltk_data] Downloading package punkt to /home/ec2-user/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ec2-user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ec2-user/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /home/ec2-user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [14]:
# transcribe_client.list_transcription_jobs()

In [47]:
transcribe_client = boto3.client("transcribe")
s3_client = boto3.client('s3')

In [48]:
import boto3
import time
from time import sleep

In [52]:

def do_transcription_job(transcribe_job_name, media_input_uri, bucket, transcribe_output_filename):
    response = transcribe_client.start_transcription_job(
        TranscriptionJobName=transcribe_job_name,
        Media={'MediaFileUri': media_input_uri},
        MediaFormat='mp4',
        LanguageCode='en-US',
        OutputBucketName=bucket,
        OutputKey=transcribe_output_filename
    )

In [53]:
# implementing solution with amazon transcribe
# Avoid doing job transcription one by one over the videos waiting every job is finished
# First, doing job of all videos and then pulling all together :)
#create input paramters for job_name and job_uri
# loop on every video file listed

# Inicializar clientes

output_files=[]
transcribe_output_prefix = 'transcribed'
for key in conn.list_objects_v2(Bucket=bucket, Prefix='input')['Contents']:
    if 'temp' in key['Key']:
        continue
    object_name=key['Key']
    media_input_uri = f's3://{bucket}/{object_name}'

    #create the transcription job
    job_uuid = uuid.uuid1()
    transcribe_job_name = f"transcribe-job-{job_uuid}"
    output_file = object_name.split('.')[0].replace(" ","_")
    transcribe_output_filename = f'{transcribe_output_prefix}-{output_file}.txt'
    output_files.append([transcribe_output_filename,object_name,""])
    print(f'{media_input_uri} transcribed to {transcribe_output_filename}')

    do_transcription_job(transcribe_job_name, media_input_uri, bucket, transcribe_output_filename)

s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod01_Course Overview.mp4 transcribed to transcribed-input/Mod01_Course_Overview.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Intro.mp4 transcribed to transcribed-input/Mod02_Intro.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect01.mp4 transcribed to transcribed-input/Mod02_Sect01.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect02.mp4 transcribed to transcribed-input/Mod02_Sect02.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect03.mp4 transcribed to transcribed-input/Mod02_Sect03.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect04.mp4 transcribed to transcribed-input/Mod02_Sect04.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_Sect05.mp4 transcribed to transcribed-input/Mod02_Sect05.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod02_WrapUp.mp4 transcribed to transcribed-input/Mod02_WrapUp.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Intro.mp4 transcribed to transcribed-input/Mod03_Intro.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect01.mp4 transcribed to transcribed-input/Mod03_Sect01.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part1.mp4 transcribed to transcribed-input/Mod03_Sect02_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part2.mp4 transcribed to transcribed-input/Mod03_Sect02_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect02_part3.mp4 transcribed to transcribed-input/Mod03_Sect02_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part1.mp4 transcribed to transcribed-input/Mod03_Sect03_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part2.mp4 transcribed to transcribed-input/Mod03_Sect03_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect03_part3.mp4 transcribed to transcribed-input/Mod03_Sect03_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part1.mp4 transcribed to transcribed-input/Mod03_Sect04_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part2.mp4 transcribed to transcribed-input/Mod03_Sect04_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect04_part3.mp4 transcribed to transcribed-input/Mod03_Sect04_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect05.mp4 transcribed to transcribed-input/Mod03_Sect05.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect06.mp4 transcribed to transcribed-input/Mod03_Sect06.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part1.mp4 transcribed to transcribed-input/Mod03_Sect07_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part2.mp4 transcribed to transcribed-input/Mod03_Sect07_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect07_part3.mp4 transcribed to transcribed-input/Mod03_Sect07_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_Sect08.mp4 transcribed to transcribed-input/Mod03_Sect08.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod03_WrapUp.mp4 transcribed to transcribed-input/Mod03_WrapUp.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Intro.mp4 transcribed to transcribed-input/Mod04_Intro.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect01.mp4 transcribed to transcribed-input/Mod04_Sect01.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part1.mp4 transcribed to transcribed-input/Mod04_Sect02_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part2.mp4 transcribed to transcribed-input/Mod04_Sect02_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_Sect02_part3.mp4 transcribed to transcribed-input/Mod04_Sect02_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod04_WrapUp.mp4 transcribed to transcribed-input/Mod04_WrapUp.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Intro.mp4 transcribed to transcribed-input/Mod05_Intro.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect01_ver2.mp4 transcribed to transcribed-input/Mod05_Sect01_ver2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect02_part1_ver2.mp4 transcribed to transcribed-input/Mod05_Sect02_part1_ver2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect02_part2.mp4 transcribed to transcribed-input/Mod05_Sect02_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part1.mp4 transcribed to transcribed-input/Mod05_Sect03_part1.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part2.mp4 transcribed to transcribed-input/Mod05_Sect03_part2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part3.mp4 transcribed to transcribed-input/Mod05_Sect03_part3.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_Sect03_part4_ver2.mp4 transcribed to transcribed-input/Mod05_Sect03_part4_ver2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod05_WrapUp_ver2.mp4 transcribed to transcribed-input/Mod05_WrapUp_ver2.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Intro.mp4 transcribed to transcribed-input/Mod06_Intro.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Sect01.mp4 transcribed to transcribed-input/Mod06_Sect01.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_Sect02.mp4 transcribed to transcribed-input/Mod06_Sect02.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod06_WrapUp.mp4 transcribed to transcribed-input/Mod06_WrapUp.txt
s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/input/Mod07_Sect01.mp4 transcribed to transcribed-input/Mod07_Sect01.txt

In [66]:
print(output_files)

[["Hi and welcome to Amazon Academy Machine Learning Foundations. In this module, you'll learn about the course objectives, various job roles in the machine learning domain, and where you can go to learn more about machine learning. After completing this module, you should be able to identify course prerequisites and objectives, indicate the role of the data scientist in business, and identify resources for further learning. We're now going to look at the prerequisites for taking this course. Before you take this course, we recommend that you first complete AWS Academy Cloud Foundations. You should also have some general technical knowledge of IT, including foundational computer literacy skills like basic computer concepts, email, file management, and a good understanding of the internet. We also recommend that you have intermediate skills with Python programming and a general knowledge of applied statistics. Finally, general business knowledge is important for this course. This includes insight into how information technology is used in business. It's also important to have business-related skill sets such as communication skills, leadership skills, and an orientation towards customer service. In this course you'll be introduced to the key concepts of machine learning, its tools, and its uses. You'll also be introduced to and work with some of the AWS services for machine learning. You'll learn how to recognize how machine learning and deep learning are part of artificial intelligence. Describe artificial intelligence and machine learning terminology. Identify how machine learning can be used to solve a business problem. Describe the machine learning process. List the tools available to data scientists. And identify when to use machine learning instead of traditional software development methods. As part of this course, you'll also learn how to implement a machine learning pipeline. This includes how to formulate a problem from a business request, obtain and secure data for machine learning, build a Jupiter notebook by using Amazon Sage Maker. Outline the process for evaluating data. Explain why data needs to be preprocessed. And use open source tools to examine and preprocess data. You will also use Amazon Sage Maker to train and host a machine learning model. Use cross validation to test the performance of a machine learning model. Use a hosted model for inference. Create an Amazon Sage Maker hyperparameter tuning job to optimize a model's effectiveness. And finally, how to use managed Amazon Machine Learning Services to solve specific machine learning problems in forecasting, computer vision, and natural language processing. We'll now review the course outline. To achieve the course objectives, you'll complete the following modules. To start, in module 2, you'll get an introduction to machine learning. In module 3, you'll learn how to implement a machine learning pipeline with Amazon Sage Maker. Modules 45, and 6 describe how to apply managed Amazon Machine Learning Services for problems in forecasting, computer vision, and natural language processing. Finally, module 7 is a summary of the course. It also includes an overview of steps you can take to work towards the AWS Certified Machine Learning Specialty. The next 5 slides provide more detail about the subtopics covered in each module. The purpose of module 2 is to introduce you to major concepts for understanding machine learning. Section 1 describes the overall field of machine learning and how machine learning relates to artificial intelligence and deep learning. In section 2, you'll learn about some of the most common business problems you can solve with machine learning. Section 3 describes the general workflow for solving machine learning problems. You'll also learn some of the more common machine learning terms. In section 4, you'll review some of the commonly used tools by machine learning professionals. And lastly, in Section 5, you'll get an overview of some of the common challenges you'll face when working with machine learning problems. In module 3 you'll get an introduction to Amazon Sage Maker and how you can use it to implement a machine learning pipeline. The module focuses on the application of machine learning to solve problems with several public domain data sets as examples of the machine learning pipeline. Section 1 introduces you to defining business problems and the data sets we'll use during this module. Section 2 through 8 describe the phases of the machine learning pipeline by using computer vision as an example application. In section 2 you'll learn how to collect and secure data. Section 3 describes different techniques for evaluating data. In section 4, you'll learn about the process of feature engineering. Section 5 describes the steps you'll take to train a model with SageMaker. In section 6, you'll get an overview of the options in Sage Maker for hosting and using a model. Finally, sections 7 and 8 cover how to evaluate and tune your model with Sage Maker. In this module, you'll be introduced to using machine learning to create forecasts based on a time series data. In section one, you'll be introduced to forecasting and some of its common applications. Section 2 outlines some of the pitfalls of using time series data to make forecasts. Finally, in section 3, you'll get an overview of how to use Amazon Forecast. In this module you'll learn about using machine learning for computer vision. Section one describes the general problems you can solve with computer vision. In section 2, you'll learn about the process for analyzing images and videos. And in Section 3 you'll learn the steps you'll need to take to prepare data sets for computer vision. In this module, you'll be introduced to natural language processing with machine learning. In section one, you'll learn about the general set of problems you can solve with natural language processing. Section 2 reviews some of the managed Amazon machine learning services you can use to address natural language processing problems. These services include Amazon Transcribe, Amazon Translate, Amazon Lex, Amazon Comprehend, and Amazon Poly. Module 7 is the final module of the course. In this module, you'll review what you've learned throughout this course. You'll also be introduced to the next steps you should take if you want to achieve the AWS Certified Machine Learning Specialty. Section one of this module summarizes the topics you've covered in this course. In section 2 you'll learn more about the AWS documentation. You'll also review two common frameworks for applying AWS services. And finally, Section 3 describes the steps you should take if you want to continue working towards the AWS Certified Machine Learning Specialty. In this section, you'll learn about some of the more common job roles for machine learning professionals. If you're interested in a data scientist role, focus on developing analytical, statistical, and programming skills. As a data scientist, you'll use those skills to collect, analyze, and interpret large data sets. Some universities now offer degrees in data science, but data scientists often have degrees in related fields like statistics, math, computer science, or economics. As a data scientist, you'll need technical competencies in statistics, machine learning, programming languages, and data analytics. If you'd like to have a career as a machine learning engineer, the skills you'll need will be similar to a data scientist's skill set. Like data scientists, machine learning engineers also require technical competencies in statistics and machine learning. However, you'll focus more on programming skills and software architecture than analysis and interpretation. As a machine learning engineer, you'll apply those programming and architecture skills to design and develop machine learning systems. Machine learning engineers often have previous experience with software development, and they rely more heavily on programming and software engineering than other machine learning roles. You might also be interested in a career in science where you can apply machine learning technology to your field. Machine learning is having an impact in everything from astronomy to zoology, so there are many different paths open to you. As an applied science researcher, your primary focus will be on the type of science you're working on. You'll need some of the same skills as a data scientist, but you'll also need to know how to apply those skills to your chosen domain. Thus, applied science rules also require technical competencies in statistics and machine learning. Many software developers are now integrating machine learning into their applications. If you're interested in a career as a software developer, you should also include machine learning technology in your studies. As a machine learning developer, your primary focus will be software development skills, but you'll also need some of the same skills as a data scientist, so make sure you take coursework in statistics and applied mathematics. And here's a final note for this module. We recommend reviewing your student guide. In your student guide, you'll find links to documentation and other resources you'll use throughout the course. That's it for this introduction. Thanks for watching. We'll see you in the next video.", 'input/Mod01_Course Overview.mp4', ''], ["Hi and welcome to module 2 of AWS Academy Machine Learning. In this module, we're going to introduce machine learning. We'll first look at the business problems that can be solved by machine learning. We'll then talk about terminology, process, tools, and some of the challenges you'll face. After completing this module, you should be able to recognize how machine learning and deep learning are part of artificial intelligence. Describe artificial intelligence and machine learning terminology. Identify how machine learning can be used to solve a business problem. Describe the machine learning process. List the tools available to data scientists. And identify when to use machine learning instead of traditional software development methods. You're now ready to get started with section one. See you in the next video.", 'input/Mod02_Intro.mp4', ''], ["Hi and welcome to section one. In this section, we're going to talk about what machine learning is. This course is an introduction to machine learning, which is also known as ML, but first we'll discuss where machine learning fits into the larger picture. Machine learning is a subset of artificial intelligence or AI. This is a broad branch of computer science that's focused on building machines that can do human tasks. Deep learning is a subdomain of machine learning. To understand where these all fit together, we'll discuss each one. As we just mentioned, machine learning is a subset of a broader computer science field known as artificial intelligence. AI focuses on building machines that can perform tasks a human would typically perform. In contemporary popular culture, you've probably seen AIs in movies, television, or works of fiction. For example, you might have seen AIs that control the world around them or that start acting on their own initiative. These AIs started as computer agents that perceive their environments and take actions to achieve a specific goal, though maybe not the outcome their creators originally wished for. Other fictional AI's interact extensively with humans as helpers or workers, and they generally do a better job working with humanity, but they're more general in purpose. These kinds of AIs are examples of artificial general intelligence or AGI. They have the capacity to learn or understand any task that a human can. AI problems typically span many fields of research, such as natural language processing, reasoning, knowledge representation, learning, perception, and physical environment interaction. AI isn't yet a reality for us, unless we're all truly living in a simulation. But every year, we move closer to it in each of those areas. You might have also read or seen commentary on the ethics of creating AI. Not all views are positive, perhaps partly in fear of the malicious fictional AIs that want to destroy humanity or use them as power sources. Or perhaps they're concerned about the risk of mass unemployment because an intelligent machine could work 24/7 and not need any breaks. Don't worry though, we're not going to build the next rogue AI in this course, maybe in the next one. If you do a search, you'll probably find many definitions of machine learning. There isn't a universally agreed upon definition, so we'll start by looking at a couple of definitions. For example, we could say machine learning is the scientific study of algorithms and statistical models to perform a task by using inference instead of instructions. This isn't a bad starting point. The key point here is using algorithms and statistical models instead of instructions. To help you better understand this, we'll apply this idea to a concrete example. Suppose you need to write an application that determines if an email message is spam or not. Without machine learning, you'd need to write a complex series of decision statements using if and else statements. You'd also need to use words in the subject or body, the number of links, and the length of the message to determine if an email message is spam. It would be hard and labor intensive to build a large set of rules covering every possibility. With machine learning, however, you could use a list of email messages that were marked as spam or not spam and train a machine learning model. The model would then learn which patterns of words, length, and other attributes are good indicators of spam messages. If you presented the model with an email message it hadn't seen before, the model would perform a prediction to say whether the message was spam or not spam. Deep learning represents a significant leap forward in the capabilities for artificial intelligence and machine learning. The theory behind deep learning was created from how the human brain works. An artificial neural network, or ANN is inspired by the biological neurons found in the brain. Although the implementation has become very different. Artificial neurons have one or more inputs and a single output. These neurons fire or activate their outputs based on a transformation of the inputs. A neural network is composed of layers of these artificial neurons with connections between the layers. There are typically input, output, and hidden layers in the network. The output of a single neuron connects to the inputs of all the neurons in the next layer. The network is then asked to solve a problem. The input layer is populated from the training data, and the neurons activate throughout the layers until an answer is presented in the output layer. The accuracy of the output is then measured. If the output doesn't meet your threshold, the training is repeated, but with slight changes to the weights of the connections between neurons. The neural network will do this repeatedly each time it strengthens the connections that lead to success and diminishes the connections that lead to failure. As you'll see in this course, machine learning practitioners spend a lot of time optimizing the ML models, selecting the best data features to train with, and selecting the models with the best results. In contrast, deep learning practitioners spend almost no time on those tasks. Instead, they spend their time modeling data with different ANN architectures. Though the theory for deep learning goes back decades, the hardware needed to run deep learning problems wasn't generally accessible until recently. But now that it's available, you can use deep learning to address problems that are more complex than the problems you could have worked on before. Mainstream machine learning is a recent occurrence. Rapid advancements in machine and deep learning only started around the mid 2000s. This is partly because Moore's Law and the rise of cloud computing resulted in easier access to larger, faster, and cheaper compute and storage capabilities. You can now rent computing power for a few hours for pennies. Before this, you needed substantial investments to buy and operate large scale compute clusters on your own. In 2012, neural networks started to be used in the ImageNet Large Scale Visual recognition Challenge, a machine learning competition for image recognition. The accuracy rate jumped up to about 82% and has been steadily climbing ever since. In fact, it exceeded human performance in 2015. Here are some of the key takeaways for this section. First, artificial intelligence is the broad field of building machines to perform human tasks. Also, machine learning is a subset of AI. It focuses on using data to train machine learning models so they can make predictions. Deep learning is a technique inspired from human biology. It uses layers of artificial neurons to build networks that solve problems. And last, advancements in technology, cloud computing, and algorithm development have led to a corresponding advance in machine learning capabilities and applications. That's it for this section. We'll see you in the next video.", 'input/Mod02_Sect01.mp4', ''], ["Hi and welcome back. In this section, we're going to look at the types of business problems machine learning can help you solve. Machine learning is used all across your digital lives. Your email spam filter is the result of a machine learning program that was trained with examples of spam and regular email messages. Based on books you're reading or products you bought, machine learning programs can predict other books or products you're likely to be interested in. Again, the machine learning program was trained with data from other readers' habits and purchases. When detecting credit card fraud, the machine learning program was trained on examples of transactions that turned out to be fraud, along with normal transactions. You can probably think of many more examples, from social media applications using facial detection to group your photos, to detecting brain tumors in brain scans, or finding anomalies in X-rays. There are 3 main types of machine learning. There's supervised learning, where a model uses known inputs and outputs to generalize future outputs. There's unsupervised learning, where the model doesn't know inputs or outputs, so it finds patterns in the data without help. And there's reinforcement learning, where the model interacts with its environment and learns to take actions that will maximize rewards. It's important to know the different types of ML because the type will guide you towards selecting algorithms that make sense for solving your business problem. Let's look more into each of these types. Supervised learning is a popular type of ML because it's widely applicable. It's called supervised learning, because there needs to be a supervisor, a teacher who can show the right answers, so to speak. Like any student, a supervised algorithm needs to learn by example. Essentially, it needs a teacher who uses training data to help it determine the patterns and relationships between the inputs and outputs. If you want to build an application to detect credit card fraud, you'd need training data that includes examples of fraud and examples of normal transactions. Within supervised learning, there are different types of problems, classification and regression. There are two subtypes of classification problems. The first is binary classification. Think back to the example with identifying fraudulent transactions. The target variable in this example is limited to two options fraudulent or not fraudulent. This is a binary classification problem. There are also multi-class classification problems. These ML problems classify an observation into one of 3 or more categories. Say that you have an 

In [110]:
job=None
while True:
    job = transcribe_client.get_transcription_job(TranscriptionJobName = transcribe_job_name)
    if job['TranscriptionJob']['TranscriptionJobStatus'] in ['COMPLETED','FAILED']:
        break
    print('.', end='')
    sleep(20)
        
print(job['TranscriptionJob']['TranscriptionJobStatus'])

COMPLETED

In [111]:
import boto3, json

# Force a clean session with minimal headers
session = boto3.Session(region_name='us-east-1')
s3_client = session.client('s3', config=boto3.session.Config(
    signature_version='s3v4',
    retries={'max_attempts': 3}
))

transcribed_text = []

for transcribe_output_filename in output_files:
    s3_key = transcribe_output_filename[0]
    
    # Skip entries that were already replaced with text (not a file path)
    if not s3_key.startswith('transcribed'):
        print(f"Skipping (already text or wrong format): {s3_key[:60]}")
        continue
    
    try:
        result = s3_client.get_object(Bucket=bucket, Key=s3_key)
        data = json.loads(result['Body'].read().decode('utf-8'))
        transcription = data['results']['transcripts'][0]['transcript']
        transcribe_output_filename[0] = transcription
        transcribed_text.append(transcription)
        print(f"Loaded: {s3_key[:60]}")
    except Exception as e:
        print(f"FAILED key='{s3_key}' | {type(e).__name__}: {e}")
        break

Skipping (already text or wrong format): Hi and welcome to Amazon Academy Machine Learning Foundation
Skipping (already text or wrong format): Hi and welcome to module 2 of AWS Academy Machine Learning.
Skipping (already text or wrong format): Hi and welcome to section one. In this section, we're going
Skipping (already text or wrong format): Hi and welcome back. In this section, we're going to look at
Skipping (already text or wrong format): Hi and welcome back. This is section 3, and we're going to g
Skipping (already text or wrong format): Welcome back. In this section, we'll look at some of the too
Skipping (already text or wrong format): Hi, welcome back. This is section 5, and we're going to disc
Skipping (already text or wrong format): It's now time to review the module. Here are the main takeaw
Skipping (already text or wrong format): Welcome back to AWS Academy of Machine Learning. This is mod
Skipping (already text or wrong format): Hi and welcome back to module 3. This is section 1, and we'r
Skipping (already text or wrong format): Hi, welcome back. We're now going to look at a few ways you
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring data collection b
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring data collection b
Skipping (already text or wrong format): Hi and welcome back. This is section 3, and we're going to c
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring how to describe y
Skipping (already text or wrong format): Hi. Welcome back. Now we'll review how to find correlations
Skipping (already text or wrong format): Hi and welcome to section 4. In this section, we're going to
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring feature engineeri
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring feature engineeri
Skipping (already text or wrong format): Hi, welcome back to module 3. This is section 5 on training.
Skipping (already text or wrong format): Hi and welcome back. This is section 6, and we're going to l
Skipping (already text or wrong format): Hi, welcome back to module 3. In this section, we'll look at
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring how to evaluate y
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring how to evaluate y
Skipping (already text or wrong format): Hi and welcome back to module 3. This is section 8. In this
Skipping (already text or wrong format): It's now time to review the module and wrap up with a knowle
Skipping (already text or wrong format): Hi and welcome to module 4 of AWS Academy Machine Learning.
Skipping (already text or wrong format): Hi and welcome to section one. We'll get started by reviewin
Skipping (already text or wrong format): Hi and welcome back. This is section 2, and we're going to f
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring wrangling time se
Skipping (already text or wrong format): Hi and welcome back. In this section, we'll look at how you
Skipping (already text or wrong format): Hi, welcome back. It's now time to review the module and wra
Skipping (already text or wrong format): Welcome back to AWS Academy of Machine Learning. This is mod
Skipping (already text or wrong format): Hi, welcome back. This is section one, and we're going to in
Skipping (already text or wrong format): Welcome back. In this section, we'll explore image analysis
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring image analysis wi
Skipping (already text or wrong format): In this section, we'll look at preparing custom data sets fo
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring video analysis by
Skipping (already text or wrong format): Hi. Welcome back. We'll continue exploring video analysis by
Skipping (already text or wrong format): Hi, welcome back. We'll continue exploring video analysis by
Skipping (already text or wrong format): It's now time to summarize some of the main points in this m
Skipping (already text or wrong format): Hi and welcome to module 6 of AWS Academy Machine Learning I
Skipping (already text or wrong format): We'll get started by reviewing what natural language process
Skipping (already text or wrong format): Welcome back. In this section, we'll review 5 managed machin
Skipping (already text or wrong format): Welcome back. It's now time to review the module and wrap it
Skipping (already text or wrong format): Welcome to module 7, course wrap up. Congratulations on comp

In [112]:
print(output_files[1])

["Hi and welcome to module 2 of AWS Academy Machine Learning. In this module, we're going to introduce machine learning. We'll first look at the business problems that can be solved by machine learning. We'll then talk about terminology, process, tools, and some of the challenges you'll face. After completing this module, you should be able to recognize how machine learning and deep learning are part of artificial intelligence. Describe artificial intelligence and machine learning terminology. Identify how machine learning can be used to solve a business problem. Describe the machine learning process. List the tools available to data scientists. And identify when to use machine learning instead of traditional software development methods. You're now ready to get started with section one. See you in the next video.", 'input/Mod02_Intro.mp4', '']

## 3. Normalizing the text
([Go to top](#Capstone-8:-Bringing-It-All-Together))

Use this section to perform any text normalization steps that are necessary for your solution.

### Reading the dataset:

In [116]:
import pandas as pd

# Rebuild df with correct column names matching what's in output_files
df = pd.DataFrame(output_files, columns=['Transcription', 'Video', 'Transcription_normalized'])

pd.set_option('display.max_colwidth', 150)

In [117]:
df.head()

,Transcription,Video,Transcription_normalized
0,"Hi and welcome to Amazon Academy Machine Learning Foundations. In this module, you'll learn about the course objectives, various job roles in the ...",input/Mod01_Course Overview.mp4,
1,"Hi and welcome to module 2 of AWS Academy Machine Learning. In this module, we're going to introduce machine learning. We'll first look at the bus...",input/Mod02_Intro.mp4,
2,"Hi and welcome to section one. In this section, we're going to talk about what machine learning is. This course is an introduction to machine lear...",input/Mod02_Sect01.mp4,
3,"Hi and welcome back. In this section, we're going to look at the types of business problems machine learning can help you solve. Machine learning ...",input/Mod02_Sect02.mp4,
4,"Hi and welcome back. This is section 3, and we're going to give you a quick high-level overview of machine learning terminology and a typical work...",input/Mod02_Sect03.mp4,

In [118]:
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem.wordnet import WordNetLemmatizer

tokenizer = RegexpTokenizer(r'\w+')
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def normalize_text(text):
    text = text.lower()
    tokens = tokenizer.tokenize(text)
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return ' '.join(tokens)

# Apply normalization and store back in df
df['Transcription_normalized'] = df['Transcription'].apply(normalize_text)

pd.set_option('display.max_colwidth', 150)
df.head()

,Transcription,Video,Transcription_normalized
0,"Hi and welcome to Amazon Academy Machine Learning Foundations. In this module, you'll learn about the course objectives, various job roles in the ...",input/Mod01_Course Overview.mp4,hi welcome amazon academy machine learning foundation module learn course objective various job role machine learning domain go learn machine lear...
1,"Hi and welcome to module 2 of AWS Academy Machine Learning. In this module, we're going to introduce machine learning. We'll first look at the bus...",input/Mod02_Intro.mp4,hi welcome module 2 aws academy machine learning module going introduce machine learning first look business problem solved machine learning talk ...
2,"Hi and welcome to section one. In this section, we're going to talk about what machine learning is. This course is an introduction to machine lear...",input/Mod02_Sect01.mp4,hi welcome section one section going talk machine learning course introduction machine learning also known ml first discus machine learning fit la...
3,"Hi and welcome back. In this section, we're going to look at the types of business problems machine learning can help you solve. Machine learning ...",input/Mod02_Sect02.mp4,hi welcome back section going look type business problem machine learning help solve machine learning used across digital life email spam filter r...
4,"Hi and welcome back. This is section 3, and we're going to give you a quick high-level overview of machine learning terminology and a typical work...",input/Mod02_Sect03.mp4,hi welcome back section 3 going give quick high level overview machine learning terminology typical workflow cover topic detail later course focus...

## 4. Extracting key phrases and topics
([Go to top](#Capstone-8:-Bringing-It-All-Together))

Use this section to extract the key phrases and topics from the videos.

In [122]:
# uploading normalized transcriptions to S3 before using amazon comprehend...
# Amazon Comprehend --> extract key phrases and topics

import boto3
import uuid
import io
from time import sleep

# Variables del lab - completar con tus valores
bucket = "c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4"
job_data_access_role = 'arn:aws:iam::992382636323:role/service-role/c193754a4977429l14270447t1-ComprehendDataAccessRole-e4DbiuHdOqqy'
comprehend_client = boto3.client('comprehend')

comprehend_input_file = 'comprehend_input.csv'
comprehend_prefix = 'comprehend'

def upload_comprehend_input(texts, bucket, prefix, filename):
    csv_buffer = io.StringIO()
    for text in texts:
        line = text.replace('\n', ' ').strip()[:5000]
        csv_buffer.write(line + '\n')
    s3_client = boto3.client('s3')
    s3_client.put_object(
        Bucket=bucket,
        Key=f'{prefix}/{filename}',
        Body=csv_buffer.getvalue()
    )
    return f's3://{bucket}/{prefix}/{filename}'

input_s3_uri = upload_comprehend_input(
    df['Transcription_normalized'].tolist(),  
    bucket,
    comprehend_prefix,
    comprehend_input_file
)
print(f'Input uploaded to: {input_s3_uri}')

Input uploaded to: s3://c193754a4977429l14270447t1w992382636323-labbucket-8ksrrtliy6u4/comprehend/comprehend_input.csv

In [124]:
# Now i'll implement amazon comprehend job, it may take a while so
# i'll do polling after this cell 

input_data_format = 'ONE_DOC_PER_LINE'
output_s3_uri = f's3://{bucket}/comprehend-output/'

# Job 1: Key Phrases
kpe_job_name = f'kpe-job-{uuid.uuid1()}'
kpe_response = comprehend_client.start_key_phrases_detection_job(
    InputDataConfig={
        'S3Uri': input_s3_uri,
        'InputFormat': input_data_format
    },
    OutputDataConfig={'S3Uri': output_s3_uri},
    DataAccessRoleArn=job_data_access_role,
    JobName=kpe_job_name,
    LanguageCode='en'
)
kpe_job_id = kpe_response['JobId']
print(f'Key Phrases job: {kpe_job_id}')

# Job 2: Entities
entity_job_name = f'entity-job-{uuid.uuid1()}'
entity_response = comprehend_client.start_entities_detection_job(
    InputDataConfig={
        'S3Uri': input_s3_uri,
        'InputFormat': input_data_format
    },
    OutputDataConfig={'S3Uri': output_s3_uri},
    DataAccessRoleArn=job_data_access_role,
    JobName=entity_job_name,
    LanguageCode='en'
)
entity_job_id = entity_response['JobId']
print(f'Entities job : {entity_job_id}')

Key Phrases job lanzado: 67d301b3baa55eb40400f3b293b3e883
Entities job lanzado: ab0a3ebe3b35ec187bb2633109cdaa4a

In [126]:
# Polling to check when jobs are finished 

kpe_done = False
entity_done = False

while not (kpe_done and entity_done):
    # Check Key Phrases
    if not kpe_done:
        kpe_job = comprehend_client.describe_key_phrases_detection_job(JobId=kpe_job_id)
        kpe_status = kpe_job['KeyPhrasesDetectionJobProperties']['JobStatus']
        if kpe_status in ['COMPLETED', 'FAILED']:
            kpe_done = True
            print(f'Key Phrases: {kpe_status}')

    # check Entities
    if not entity_done:
        entity_job = comprehend_client.describe_entities_detection_job(JobId=entity_job_id)
        entity_status = entity_job['EntitiesDetectionJobProperties']['JobStatus']
        if entity_status in ['COMPLETED', 'FAILED']:
            entity_done = True
            print(f'Entities: {entity_status}')

    if not (kpe_done and entity_done):
        print('.', end='')
        sleep(30)

print('\n Both jobs done')

.......Key Phrases: COMPLETED
Entities: COMPLETED

 Both jobs done

### Download and parse results:

In [127]:
import tarfile, json

def download_and_parse_comprehend_output(job_properties_key, job_response, output_filename):
    output_uri = job_response[job_properties_key]['OutputDataConfig']['S3Uri']
    out_bucket, out_key = output_uri.replace('s3://', '').split('/', 1)
    
    s3_client = boto3.resource('s3')
    s3_client.meta.client.download_file(out_bucket, out_key, output_filename)
    
    with tarfile.open(output_filename) as tf:
        tf.extractall()
    
    results = []
    with open('output', 'r') as f:
        for line in f:
            results.append(json.loads(line))
    return results

# Downloading key phrases...
kpe_results = download_and_parse_comprehend_output(
    'KeyPhrasesDetectionJobProperties',
    kpe_job,
    'output-kpe.tar.gz'
)

# Downloading Entities...
entity_results = download_and_parse_comprehend_output(
    'EntitiesDetectionJobProperties',
    entity_job,
    'output-entities.tar.gz'
)

print(f'Processed Key phrases documents: {len(kpe_results)}')
print(f'Processed entities (documents)   : {len(entity_results)}')

Processed Key phrases documents: 46
Processed entities (documents)   : 46

/tmp/ipykernel_9153/736880532.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tf.extractall()

## 5. Creating the dashboard
([Go to top](#Capstone-8:-Bringing-It-All-Together))

Use this section to create the dashboard for your solution.

In [136]:
# dependencies

!pip install --upgrade pip
!pip install opensearch-py
!pip install requests
!pip install requests-aws4auth

Requirement already satisfied: pip in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (26.0.1)
Collecting opensearch-py
  Downloading opensearch_py-3.1.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: urllib3!=2.2.0,!=2.2.1,<3,>=1.26.19 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from opensearch-py) (2.6.3)
Requirement already satisfied: requests<3.0.0,>=2.32.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from opensearch-py) (2.32.5)
Requirement already satisfied: python-dateutil in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from opensearch-py) (2.9.0.post0)
Requirement already satisfied: certifi>=2024.07.04 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from opensearch-py) (2026.1.4)
Collecting Events (from opensearch-py)
  Downloading Events-0.5-py3-none-any.whl.metadata (3.9 kB)
Collecting opensearch-protobufs==0.19.0 (from opensearch-py)
  Downloading opensearch_protobufs-0.19.0-py3-none-any.whl.metadata (678 bytes)
Requirement already satisfied: protobuf>=3.20.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from opensearch-protobufs==0.19.0->opensearch-py) (6.31.1)
Collecting grpcio>=1.68.1 (from opensearch-protobufs==0.19.0->opensearch-py)
  Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.0->opensearch-py) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.0->opensearch-py) (3.11)
Requirement already satisfied: typing-extensions~=4.12 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from grpcio>=1.68.1->opensearch-protobufs==0.19.0->opensearch-py) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from python-dateutil->opensearch-py) (1.17.0)
Downloading opensearch_py-3.1.0-py3-none-any.whl (385 kB)
Downloading opensearch_protobufs-0.19.0-py3-none-any.whl (39 kB)
Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 124.9 MB/s  0:00:00
Downloading Events-0.5-py3-none-any.whl (6.8 kB)
Installing collected packages: Events, grpcio, opensearch-protobufs, opensearch-py
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [opensearch-py]0m [opensearch-py]
Successfully installed Events-0.5 grpcio-1.78.0 opensearch-protobufs-0.19.0 opensearch-py-3.1.0
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests) (2026.1.4)
Collecting requests-aws4auth
  Downloading requests_aws4auth-1.3.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests-aws4auth) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->requests-aws4auth) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->requests-aws4auth) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->requests-aws4auth) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests->requests-aws4auth) (2026.1.4)
Downloading requests_aws4auth-1.3.1-py3-none-any.whl (24 kB)
Installing collected packages: requests-aws4auth
Successfully installed requests-aws4auth-1.3.1

### For dashboard visualization i'll use amazon Kibana:

In [ ]:
# first ill create open search index

my_ip = '<Your IP>'
print(my_ip)

es_client = boto3.client('es')

access_policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Action": "es:*",
                "Resource": "*",
                "Condition": { "IpAddress": { "aws:SourceIp": my_ip } }
            }
        ]
    }

190.210.32.235

In [ ]:
# Now i create OpenSearch cluster:

response = es_client.create_elasticsearch_domain(
    DomainName='nlp-lab',
    ElasticsearchVersion='7.9',
    ElasticsearchClusterConfig={
        'InstanceType': 't3.small.elasticsearch', 
        'InstanceCount': 2,
        'DedicatedMasterEnabled': False,
        'ZoneAwarenessEnabled': False
    },
    EBSOptions={
        'EBSEnabled': True,
        'VolumeType': 'gp2',
        'VolumeSize': 10
    },
    AccessPolicies=json.dumps(access_policy)
)

In [144]:

from time import sleep
alive = es_client.describe_elasticsearch_domain(DomainName='nlp-lab')
while alive['DomainStatus']['Processing']:
    print('.', end='')
    sleep(10)
    alive = es_client.describe_elasticsearch_domain(DomainName='nlp-lab')
    
print('ready!')

# Finally creating Kibana dashboard

es_domain = es_client.describe_elasticsearch_domain(DomainName='nlp-lab')
es_endpoint = es_domain['DomainStatus']['Endpoint']
print(f'https://{es_endpoint}/_plugin/kibana')

...........................................ready!
https://search-nlp-lab-3jchgtpjhui2jxvx37ub4dnyfi.us-east-1.es.amazonaws.com/_plugin/kibana

In [145]:
# import opensearch libraries

from opensearchpy import OpenSearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth
import requests

In [147]:
# creating an opensearch client

from opensearchpy import OpenSearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth
import boto3

region = 'us-east-1'
credentials = boto3.Session().get_credentials()

awsauth = AWS4Auth(
    credentials.access_key,
    credentials.secret_key,
    region,
    'es',
    session_token=credentials.token
)

es_endpoint = 'search-nlp-lab-3jchgtpjhui2jxvx37ub4dnyfi.us-east-1.es.amazonaws.com'

es = OpenSearch(
    hosts=[{'host': es_endpoint, 'port': 443}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection
)

# Verify connection
print(es.info())

{'name': 'ba41e56736b8908db01401076a36388c', 'cluster_name': '992382636323:nlp-lab', 'cluster_uuid': 'oo85VtEvTUON3vXO84E4xQ', 'version': {'number': '7.9.1', 'build_flavor': 'oss', 'build_type': 'tar', 'build_hash': 'unknown', 'build_date': '2026-02-06T12:28:17.702161Z', 'build_snapshot': False, 'lucene_version': '8.6.2', 'minimum_wire_compatibility_version': '6.8.0', 'minimum_index_compatibility_version': '6.0.0-beta1'}, 'tagline': 'You Know, for Search'}

In [151]:
# Extraer solo el texto de cada keyphrase y entity
df['KeyPhrases'] = [
    [kp['Text'] for kp in result['KeyPhrases']]
    for result in kpe_results
]

df['Entities'] = [
    [ent['Text'] for ent in result['Entities']]
    for result in entity_results
]

print(df.columns.tolist())
print(df.head(2))

['Transcription', 'Video', 'Transcription_normalized', 'KeyPhrases', 'Entities']
                                                                                                                                           Transcription  \
0  Hi and welcome to Amazon Academy Machine Learning Foundations. In this module, you'll learn about the course objectives, various job roles in the ...
1  Hi and welcome to module 2 of AWS Academy Machine Learning. In this module, we're going to introduce machine learning. We'll first look at the bus...

                             Video  \
0  input/Mod01_Course Overview.mp4
1            input/Mod02_Intro.mp4

                                                                                                                                Transcription_normalized  \
0  hi welcome amazon academy machine learning foundation module learn course objective various job role machine learning domain go learn machine lear...
1  hi welcome module 2 aws academy machine learning module going introduce machine learning first look business problem solved machine learning talk ...

                                                                                                                                              KeyPhrases  \
0  [amazon academy machine, foundation module, course objective, various job role machine, domain, machine, module, course prerequisite objective, ro...
1  [module 2 aws academy machine, module, machine, first look business problem, machine, talk terminology process tool challenge face, module, machin...

                                                                                                                                                Entities
0  [amazon, first, aws academy, python, aws, amazon, amazon, amazon, amazon, amazon, amazon, module, aws, 5 slide, section, section, section, 5, amaz...
1                                                                                                              [2, aws academy, first look, section one]

In [152]:
#indexing in opensearch

from time import sleep

index_name = 'videos'

for i, row in df.iterrows():
    document = {
        'video_name' : row['Video'],
        'transcript' : row['Transcription'],
        'normalized' : row['Transcription_normalized'],
        'keyphrases' : row['KeyPhrases'],
        'entities'   : row['Entities'],
    }
    es.index(index=index_name, body=document)

    if i % 10 == 0 and i > 0:
        print(f'Indexed {i} documents...')
        sleep(2)

print(f'Done. Total indexed: {len(df)} documents')

Indexed 10 documents...
Indexed 20 documents...
Indexed 30 documents...
Indexed 40 documents...
Done. Total indexed: 46 documents

# Congratulations!

You have completed this lab, and you can now end the lab by following the lab guide instructions.

*©2023 Amazon Web Services, Inc. or its affiliates. All rights reserved. This work may not be reproduced or redistributed, in whole or in part, without prior written permission from Amazon Web Services, Inc. Commercial copying, lending, or selling is prohibited. All trademarks are the property of their owners.*